name: Deploy to GitHub Pages - Simple

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Update browserslist database
        run: npx update-browserslist-db@latest

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd dist/public
          touch .nojekyll
          git init
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Deploying to gh-pages from @ $GITHUB_REPOSITORY@${GITHUB_SHA}"
          git push --force "https://${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git" HEAD:gh-pages
